name: SendToSlack

author: Logan Kilpatrick

description: Pings Stack Overflow for new questions of a specific tag and then sends the links to slack. 

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'cast'  
  color: 'purple'
